 CREATE TABLE IF NOT EXISTS CLIENTS(
   ID UUID PRIMARY KEY,
   CLIENT_NAME VARCHAR(50),
   PHONE_NUMBER VARCHAR(20),
   CODE_CARD VARCHAR(13),
   BONUS NUMERIC(20,2)
 );

CREATE TABLE IF NOT EXISTS DEVICES(
    CLIENT_ID UUID REFERENCES CLIENTS(ID),
    DEVICE_ID VARCHAR(50)
);